# Generated by Django 3.2.7 on 2021-10-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
