# Generated by Django 3.2.7 on 2021-10-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
