# Generated by Django 3.2.7 on 2021-10-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
